<?
$aMenuLinks = Array(
	Array(
		"vk", 
		"http://vk.com/kremlinksk", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"ok", 
		"http://www.odnoklassniki.ru/dk?st.cmd=altGroupRestricted&st.groupId=foxezjudeeklejbtdms0rapkqdfeiajalasek&tkn=5203&st.layer.cmd=PopLayerClose", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"facebook", 
		"https://www.facebook.com/kremlinksk", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"youtube", 
		"http://www.youtube.com/user/KremlinOfficial1", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"instagram", 
		"http://instagram.com/kremlinksk", 
		Array(), 
		Array(), 
		"" 
	)
);
?>